USE [master]
GO
/****** Object:  Database [SMARTRIP]    Script Date: 22/10/2024 15:28:03 ******/
CREATE DATABASE [SMARTRIP]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SMARTRIP', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\SMARTRIP.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SMARTRIP_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\SMARTRIP_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [SMARTRIP] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SMARTRIP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SMARTRIP] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SMARTRIP] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SMARTRIP] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SMARTRIP] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SMARTRIP] SET ARITHABORT OFF 
GO
ALTER DATABASE [SMARTRIP] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SMARTRIP] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SMARTRIP] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SMARTRIP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SMARTRIP] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SMARTRIP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SMARTRIP] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SMARTRIP] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SMARTRIP] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SMARTRIP] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SMARTRIP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SMARTRIP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SMARTRIP] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SMARTRIP] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SMARTRIP] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SMARTRIP] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SMARTRIP] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SMARTRIP] SET RECOVERY FULL 
GO
ALTER DATABASE [SMARTRIP] SET  MULTI_USER 
GO
ALTER DATABASE [SMARTRIP] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SMARTRIP] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SMARTRIP] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SMARTRIP] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SMARTRIP] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'SMARTRIP', N'ON'
GO
ALTER DATABASE [SMARTRIP] SET QUERY_STORE = OFF
GO
USE [SMARTRIP]
GO
/****** Object:  User [alumno]    Script Date: 22/10/2024 15:28:03 ******/
CREATE USER [alumno] FOR LOGIN [alumno] WITH DEFAULT_SCHEMA=[dbo]
GO
/****** Object:  Table [dbo].[USUARIO]    Script Date: 22/10/2024 15:28:03 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USUARIO](
	[nombre] [varchar](50) NULL,
	[apellido] [varchar](50) NULL,
	[fechaNacimiento] [date] NULL,
	[genero] [varchar](10) NULL,
	[email] [varchar](50) NOT NULL,
	[telefono] [int] NOT NULL,
	[contraseña] [varchar](50) NULL
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [SMARTRIP] SET  READ_WRITE 
GO
